name: Publish Packages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/ExpressiveDynamoDB

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.401
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Pull DynamoDB Docker Image
      run: docker pull amazon/dynamodb-local
    - name: Test
      run: |
        docker run -d -p 8000:8000 amazon/dynamodb-local
        dotnet test --no-restore --verbosity normal
      working-directory: src
      env:
        AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    - name: Publish
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/ExpressiveDynamoDB/ExpressiveDynamoDB.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}